-- 运维问题 / 事项关系增量脚本
-- 适用于已导入基础运维表的环境，可重复执行。

CREATE TABLE IF NOT EXISTS `ops_issue` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `issue_no` varchar(64) NOT NULL COMMENT '问题编号',
    `issue_type` varchar(32) DEFAULT 'OTHER' COMMENT '问题类型',
    `system_id` bigint(20) DEFAULT NULL COMMENT '系统ID',
    `system_name` varchar(100) DEFAULT NULL COMMENT '系统名称',
    `module_code` varchar(32) DEFAULT NULL COMMENT '所属模块',
    `issue_title` varchar(200) NOT NULL COMMENT '问题标题',
    `issue_desc` text COMMENT '问题描述',
    `source_type` varchar(32) DEFAULT NULL COMMENT '发现来源',
    `impact_scope` varchar(500) DEFAULT NULL COMMENT '影响范围',
    `priority` varchar(16) DEFAULT 'P2' COMMENT '优先级',
    `founder` varchar(50) DEFAULT NULL COMMENT '发现人',
    `found_time` datetime DEFAULT NULL COMMENT '发现时间',
    `owner_id` bigint(20) DEFAULT NULL COMMENT '负责人ID',
    `owner_name` varchar(50) DEFAULT NULL COMMENT '负责人',
    `status` varchar(32) DEFAULT 'PENDING' COMMENT '当前状态',
    `handle_method` varchar(32) DEFAULT NULL COMMENT '处理方式',
    `handle_result` text COMMENT '处理结果',
    `root_cause` varchar(32) DEFAULT NULL COMMENT '根因分类',
    `work_item_id` bigint(20) DEFAULT NULL COMMENT '关联事项ID',
    `related_bug_no` varchar(64) DEFAULT NULL COMMENT '关联Bug编号',
    `related_req_no` varchar(64) DEFAULT NULL COMMENT '关联需求编号',
    `related_change_no` varchar(64) DEFAULT NULL COMMENT '关联变更编号',
    `plan_finish_time` datetime DEFAULT NULL COMMENT '计划完成时间',
    `actual_finish_time` datetime DEFAULT NULL COMMENT '实际完成时间',
    `overdue_flag` char(1) DEFAULT '0' COMMENT '是否逾期(0否 1是)',
    `del_flag` char(1) DEFAULT '0' COMMENT '删除标记(0正常 1删除)',
    `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_issue_no` (`issue_no`),
    KEY `idx_issue_type` (`issue_type`),
    KEY `idx_status` (`status`),
    KEY `idx_priority` (`priority`),
    KEY `idx_system_id` (`system_id`),
    KEY `idx_owner_id` (`owner_id`),
    KEY `idx_found_time` (`found_time`),
    KEY `idx_work_item_id` (`work_item_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='运维问题';

CREATE TABLE IF NOT EXISTS `ops_item_relation` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源对象类型',
    `source_id` bigint(20) DEFAULT NULL COMMENT '来源对象ID',
    `source_no` varchar(64) DEFAULT NULL COMMENT '来源编号',
    `target_type` varchar(32) NOT NULL COMMENT '目标对象类型',
    `target_id` bigint(20) DEFAULT NULL COMMENT '目标对象ID',
    `target_no` varchar(64) DEFAULT NULL COMMENT '目标编号',
    `relation_type` varchar(32) NOT NULL COMMENT '关系类型',
    `relation_desc` varchar(1000) DEFAULT NULL COMMENT '关系说明',
    `relation_time` datetime DEFAULT NULL COMMENT '关联时间',
    `del_flag` char(1) DEFAULT '0' COMMENT '删除标记(0正常 1删除)',
    `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_item_relation` (`source_type`, `source_id`, `target_type`, `target_id`, `relation_type`),
    KEY `idx_source` (`source_type`, `source_id`),
    KEY `idx_source_no` (`source_no`),
    KEY `idx_target` (`target_type`, `target_id`),
    KEY `idx_target_no` (`target_no`),
    KEY `idx_relation_type` (`relation_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='事项关系表';
