-- 运维模块字典项

insert ignore into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark) values
('运维系统类型', 'ops_system_type', '0', 'admin', sysdate(), '运维系统资产类型'),
('运维重要等级', 'ops_importance_level', '0', 'admin', sysdate(), '运维系统重要程度'),
('运维系统状态', 'ops_system_status', '0', 'admin', sysdate(), '系统资产生命周期状态'),
('运维成员角色', 'ops_team_role', '0', 'admin', sysdate(), '运维团队成员角色'),
('运维在岗状态', 'ops_on_job_status', '0', 'admin', sysdate(), '团队成员在岗状态'),
('供应商服务范围', 'ops_service_scope', '0', 'admin', sysdate(), '供应商服务范围'),
('供应商SLA等级', 'ops_sla_level', '0', 'admin', sysdate(), '供应商服务SLA等级'),
('班次类型', 'ops_shift_type', '0', 'admin', sysdate(), '值班班次类型'),
('班次状态', 'ops_shift_status', '0', 'admin', sysdate(), '值班班次状态'),
('日志类型', 'ops_log_type', '0', 'admin', sysdate(), '值班日志类型'),
('严重程度', 'ops_severity', '0', 'admin', sysdate(), '严重程度'),
('是否升级', 'ops_yes_no', '0', 'admin', sysdate(), '是否类字典'),
('故障级别', 'ops_fault_level', '0', 'admin', sysdate(), '故障严重级别'),
('故障状态', 'ops_fault_status', '0', 'admin', sysdate(), '故障处理状态'),
('巡检状态', 'ops_health_status', '0', 'admin', sysdate(), '巡检指标状态'),
('巡检结果', 'ops_inspection_result', '0', 'admin', sysdate(), '巡检整体结果'),
('备份类型', 'ops_backup_type', '0', 'admin', sysdate(), '备份类型'),
('备份结果', 'ops_backup_result', '0', 'admin', sysdate(), '备份执行结果'),
('恢复验证', 'ops_restore_tested', '0', 'admin', sysdate(), '恢复验证结果'),
('变更类型', 'ops_change_type', '0', 'admin', sysdate(), '变更类型'),
('风险等级', 'ops_risk_level', '0', 'admin', sysdate(), '变更风险等级'),
('变更结果', 'ops_change_result', '0', 'admin', sysdate(), '变更执行结果'),
('任务状态', 'ops_task_status', '0', 'admin', sysdate(), '周运维任务状态'),
('运维类型', 'ops_operation_type', '0', 'admin', sysdate(), '关键运维类型'),
('执行结果', 'ops_operation_result', '0', 'admin', sysdate(), '运维执行结果'),
('知识分类', 'ops_knowledge_category', '0', 'admin', sysdate(), '知识库分类'),
('发布状态', 'ops_publish_status', '0', 'admin', sysdate(), '知识发布状态');

delete from sys_dict_data where dict_type in (
  'ops_system_type',
  'ops_importance_level',
  'ops_system_status',
  'ops_team_role',
  'ops_on_job_status',
  'ops_service_scope',
  'ops_sla_level',
  'ops_shift_type',
  'ops_shift_status',
  'ops_log_type',
  'ops_severity',
  'ops_yes_no',
  'ops_fault_level',
  'ops_fault_status',
  'ops_health_status',
  'ops_inspection_result',
  'ops_backup_type',
  'ops_backup_result',
  'ops_restore_tested',
  'ops_change_type',
  'ops_risk_level',
  'ops_change_result',
  'ops_task_status',
  'ops_operation_type',
  'ops_operation_result',
  'ops_knowledge_category',
  'ops_publish_status'
);

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark) values
(1, '核心业务', '1', 'ops_system_type', '', 'danger', 'Y', '0', 'admin', sysdate(), '核心交易、清算等业务系统'),
(2, '支撑系统', '2', 'ops_system_type', '', 'warning', 'N', '0', 'admin', sysdate(), '支撑业务运营的系统'),
(3, '基础设施', '3', 'ops_system_type', '', 'info', 'N', '0', 'admin', sysdate(), '网络、数据库、中间件等基础设施'),

(1, '核心', '1', 'ops_importance_level', '', 'danger', 'Y', '0', 'admin', sysdate(), '核心等级'),
(2, '重要', '2', 'ops_importance_level', '', 'warning', 'N', '0', 'admin', sysdate(), '重要等级'),
(3, '一般', '3', 'ops_importance_level', '', 'info', 'N', '0', 'admin', sysdate(), '一般等级'),

(1, '运行中', '1', 'ops_system_status', '', 'success', 'Y', '0', 'admin', sysdate(), '正常运行'),
(2, '停用', '2', 'ops_system_status', '', 'warning', 'N', '0', 'admin', sysdate(), '暂停使用'),
(3, '下线', '3', 'ops_system_status', '', 'info', 'N', '0', 'admin', sysdate(), '已下线'),

(1, '运维负责人', '1', 'ops_team_role', '', 'danger', 'N', '0', 'admin', sysdate(), '负责整体运维'),
(2, '值班长', '2', 'ops_team_role', '', 'warning', 'N', '0', 'admin', sysdate(), '负责值班协调'),
(3, '运维工程师', '3', 'ops_team_role', '', 'primary', 'Y', '0', 'admin', sysdate(), '负责日常运维'),
(4, '巡检员', '4', 'ops_team_role', '', 'info', 'N', '0', 'admin', sysdate(), '负责巡检执行'),

(1, '在岗', '1', 'ops_on_job_status', '', 'success', 'Y', '0', 'admin', sysdate(), '当前在岗'),
(2, '休假', '2', 'ops_on_job_status', '', 'warning', 'N', '0', 'admin', sysdate(), '休假中'),
(3, '离职', '3', 'ops_on_job_status', '', 'info', 'N', '0', 'admin', sysdate(), '已离职'),

(1, '开发支持', '1', 'ops_service_scope', '', 'primary', 'N', '0', 'admin', sysdate(), '开发与缺陷支持'),
(2, '运维支持', '2', 'ops_service_scope', '', 'success', 'Y', '0', 'admin', sysdate(), '运维保障支持'),
(3, '硬件支持', '3', 'ops_service_scope', '', 'warning', 'N', '0', 'admin', sysdate(), '硬件设备支持'),
(4, '综合支持', '4', 'ops_service_scope', '', 'info', 'N', '0', 'admin', sysdate(), '综合服务支持'),

(1, 'P1', 'P1', 'ops_sla_level', '', 'danger', 'Y', '0', 'admin', sysdate(), '最高服务等级'),
(2, 'P2', 'P2', 'ops_sla_level', '', 'warning', 'N', '0', 'admin', sysdate(), '标准服务等级'),
(3, 'P3', 'P3', 'ops_sla_level', '', 'info', 'N', '0', 'admin', sysdate(), '基础服务等级'),

(1, '白班', '1', 'ops_shift_type', '', 'success', 'Y', '0', 'admin', sysdate(), '白班'),
(2, '夜班', '2', 'ops_shift_type', '', 'primary', 'N', '0', 'admin', sysdate(), '夜班'),
(3, '节假日', '3', 'ops_shift_type', '', 'warning', 'N', '0', 'admin', sysdate(), '节假日值班'),
(1, '进行中', '1', 'ops_shift_status', '', 'success', 'Y', '0', 'admin', sysdate(), '进行中'),
(2, '已交接', '2', 'ops_shift_status', '', 'primary', 'N', '0', 'admin', sysdate(), '已交接'),
(3, '已结束', '3', 'ops_shift_status', '', 'info', 'N', '0', 'admin', sysdate(), '已结束'),

(1, '日常', '1', 'ops_log_type', '', 'info', 'Y', '0', 'admin', sysdate(), '日常日志'),
(2, '事件', '2', 'ops_log_type', '', 'primary', 'N', '0', 'admin', sysdate(), '事件记录'),
(3, '告警', '3', 'ops_log_type', '', 'warning', 'N', '0', 'admin', sysdate(), '告警记录'),
(4, '交接', '4', 'ops_log_type', '', 'success', 'N', '0', 'admin', sysdate(), '交接记录'),
(1, '普通', '1', 'ops_severity', '', 'info', 'Y', '0', 'admin', sysdate(), '普通'),
(2, '重要', '2', 'ops_severity', '', 'warning', 'N', '0', 'admin', sysdate(), '重要'),
(3, '紧急', '3', 'ops_severity', '', 'danger', 'N', '0', 'admin', sysdate(), '紧急'),
(1, '否', '0', 'ops_yes_no', '', 'info', 'Y', '0', 'admin', sysdate(), '否'),
(2, '是', '1', 'ops_yes_no', '', 'danger', 'N', '0', 'admin', sysdate(), '是'),

(1, '一般', '1', 'ops_fault_level', '', 'info', 'Y', '0', 'admin', sysdate(), '一般故障'),
(2, '严重', '2', 'ops_fault_level', '', 'warning', 'N', '0', 'admin', sysdate(), '严重故障'),
(3, '紧急', '3', 'ops_fault_level', '', 'danger', 'N', '0', 'admin', sysdate(), '紧急故障'),
(1, '发现', '1', 'ops_fault_status', '', 'warning', 'Y', '0', 'admin', sysdate(), '已发现'),
(2, '处理中', '2', 'ops_fault_status', '', 'primary', 'N', '0', 'admin', sysdate(), '处理中'),
(3, '已恢复', '3', 'ops_fault_status', '', 'success', 'N', '0', 'admin', sysdate(), '已恢复'),
(4, '已关闭', '4', 'ops_fault_status', '', 'info', 'N', '0', 'admin', sysdate(), '已关闭'),

(1, '正常', '1', 'ops_health_status', '', 'success', 'Y', '0', 'admin', sysdate(), '正常'),
(2, '异常', '2', 'ops_health_status', '', 'danger', 'N', '0', 'admin', sysdate(), '异常'),
(3, '未检查', '3', 'ops_health_status', '', 'info', 'N', '0', 'admin', sysdate(), '未检查'),
(1, '正常', '1', 'ops_inspection_result', '', 'success', 'Y', '0', 'admin', sysdate(), '巡检正常'),
(2, '异常', '2', 'ops_inspection_result', '', 'danger', 'N', '0', 'admin', sysdate(), '巡检异常'),
(3, '已处理', '3', 'ops_inspection_result', '', 'primary', 'N', '0', 'admin', sysdate(), '异常已处理'),

(1, '全量', '1', 'ops_backup_type', '', 'primary', 'Y', '0', 'admin', sysdate(), '全量备份'),
(2, '增量', '2', 'ops_backup_type', '', 'success', 'N', '0', 'admin', sysdate(), '增量备份'),
(3, '差异', '3', 'ops_backup_type', '', 'warning', 'N', '0', 'admin', sysdate(), '差异备份'),
(1, '成功', '1', 'ops_backup_result', '', 'success', 'Y', '0', 'admin', sysdate(), '备份成功'),
(2, '失败', '2', 'ops_backup_result', '', 'danger', 'N', '0', 'admin', sysdate(), '备份失败'),
(3, '部分成功', '3', 'ops_backup_result', '', 'warning', 'N', '0', 'admin', sysdate(), '部分成功'),
(1, '未验证', '0', 'ops_restore_tested', '', 'info', 'Y', '0', 'admin', sysdate(), '未恢复验证'),
(2, '已通过', '1', 'ops_restore_tested', '', 'success', 'N', '0', 'admin', sysdate(), '恢复验证通过'),
(3, '未通过', '2', 'ops_restore_tested', '', 'danger', 'N', '0', 'admin', sysdate(), '恢复验证未通过'),

(1, '功能发布', '1', 'ops_change_type', '', 'primary', 'Y', '0', 'admin', sysdate(), '功能发布'),
(2, '配置调整', '2', 'ops_change_type', '', 'success', 'N', '0', 'admin', sysdate(), '配置调整'),
(3, '数据变更', '3', 'ops_change_type', '', 'warning', 'N', '0', 'admin', sysdate(), '数据变更'),
(4, '应急变更', '4', 'ops_change_type', '', 'danger', 'N', '0', 'admin', sysdate(), '应急变更'),
(1, '低', '1', 'ops_risk_level', '', 'success', 'Y', '0', 'admin', sysdate(), '低风险'),
(2, '中', '2', 'ops_risk_level', '', 'warning', 'N', '0', 'admin', sysdate(), '中风险'),
(3, '高', '3', 'ops_risk_level', '', 'danger', 'N', '0', 'admin', sysdate(), '高风险'),
(1, '成功', '1', 'ops_change_result', '', 'success', 'Y', '0', 'admin', sysdate(), '变更成功'),
(2, '失败', '2', 'ops_change_result', '', 'danger', 'N', '0', 'admin', sysdate(), '变更失败'),
(3, '已回滚', '3', 'ops_change_result', '', 'warning', 'N', '0', 'admin', sysdate(), '已回滚'),

(1, '未开始', '1', 'ops_task_status', '', 'info', 'Y', '0', 'admin', sysdate(), '未开始'),
(2, '进行中', '2', 'ops_task_status', '', 'primary', 'N', '0', 'admin', sysdate(), '进行中'),
(3, '已完成', '3', 'ops_task_status', '', 'success', 'N', '0', 'admin', sysdate(), '已完成'),
(4, '有风险', '4', 'ops_task_status', '', 'warning', 'N', '0', 'admin', sysdate(), '有风险'),
(1, '巡检', '1', 'ops_operation_type', '', 'success', 'Y', '0', 'admin', sysdate(), '巡检'),
(2, '发布', '2', 'ops_operation_type', '', 'primary', 'N', '0', 'admin', sysdate(), '发布'),
(3, '变更', '3', 'ops_operation_type', '', 'warning', 'N', '0', 'admin', sysdate(), '变更'),
(4, '故障处理', '4', 'ops_operation_type', '', 'danger', 'N', '0', 'admin', sysdate(), '故障处理'),
(1, '成功', '1', 'ops_operation_result', '', 'success', 'Y', '0', 'admin', sysdate(), '成功'),
(2, '失败', '2', 'ops_operation_result', '', 'danger', 'N', '0', 'admin', sysdate(), '失败'),
(3, '部分完成', '3', 'ops_operation_result', '', 'warning', 'N', '0', 'admin', sysdate(), '部分完成'),

(1, '故障处理', '1', 'ops_knowledge_category', '', 'danger', 'Y', '0', 'admin', sysdate(), '故障处理'),
(2, '巡检经验', '2', 'ops_knowledge_category', '', 'success', 'N', '0', 'admin', sysdate(), '巡检经验'),
(3, '变更发布', '3', 'ops_knowledge_category', '', 'primary', 'N', '0', 'admin', sysdate(), '变更发布'),
(4, '备份恢复', '4', 'ops_knowledge_category', '', 'warning', 'N', '0', 'admin', sysdate(), '备份恢复'),
(1, '草稿', '0', 'ops_publish_status', '', 'info', 'Y', '0', 'admin', sysdate(), '草稿'),
(2, '已发布', '1', 'ops_publish_status', '', 'success', 'N', '0', 'admin', sysdate(), '已发布');
